name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  windows-test:
    runs-on: windows-latest
    steps:
      - name: test
      - run: echo %PATH%
